# $FreeBSD: src/usr.sbin/pkg_install/lib/Makefile,v 1.18.22.1 2009/08/03 08:13:06 kensmith Exp $

LIB=	cblog_utils
INTERNALLIB=
CFLAGS+=	-I/usr/local/include -Wall -Werror
SRCS=		db.c utils.c

WARNS?=	3
#WFORMAT?=	1

.include <bsd.lib.mk>
